{% set name = "narwhals" %}
{% set version = "2.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 13e7ff5b4bb4a2f77b907c2e4d8a76e273dfc1323a3c997440a2f9fd26aed408

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - uv-build >=0.11.0,<0.12.0
  run:
    - python

test:
  imports:
    - narwhals
    - narwhals._arrow
    - narwhals._compliant
    - narwhals._constants
    - narwhals._dask
    - narwhals._duckdb
    - narwhals._duration
    - narwhals._enum
    - narwhals._expression_parsing
    - narwhals._ibis
    - narwhals._interchange
    - narwhals._namespace
    - narwhals._pandas_like
    - narwhals._polars
    - narwhals._spark_like
    - narwhals._sql
    - narwhals._translate
    - narwhals._typing_compat
    - narwhals._utils
    - narwhals.dataframe
    - narwhals.dependencies
    - narwhals.dtypes
    - narwhals.exceptions
    - narwhals.expr
    - narwhals.expr_cat
    - narwhals.expr_dt
    - narwhals.expr_list
    - narwhals.expr_name
    - narwhals.expr_str
    - narwhals.expr_struct
    - narwhals.functions
    - narwhals.group_by
    - narwhals.schema
    - narwhals.selectors
    - narwhals.series
    - narwhals.series_cat
    - narwhals.series_dt
    - narwhals.series_list
    - narwhals.series_str
    - narwhals.series_struct
    - narwhals.stable
    - narwhals.translate
    - narwhals.typing
    - narwhals.utils
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"

about:
  home: https://github.com/narwhals-dev/narwhals
  dev_url: https://github.com/narwhals-dev/narwhals
  summary: Extremely lightweight compatibility layer between pandas, Polars, cuDF, and Modin
  license: MIT
  license_file: LICENSE.md
  license_family: MIT
  description: |
    Narwhals is an extremely lightweight compatibility layer between pandas, Polars, cuDF, and Modin.
    It allows you to write code that works with all of these libraries without having to worry about
    the differences between them.
  doc_url: https://narwhals-dev.github.io/narwhals

extra:
  recipe-maintainers:
    - MarcoGorelli
    - thewchan
