{% set name = "narwhals" %}
{% set version = "0.9.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/narwhals-{{ version }}.tar.gz
  sha256: 0fa6f5932233877e766132d1619b95ae08ec1fc9fb33c08849a2279216caba36

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8

test:
  imports:
    - narwhals
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://marcogorelli.github.io/narwhals/
  dev_url: https://github.com/MarcoGorelli/narwhals
  summary: Extremely lightweight compatibility layer between pandas, Polars, cuDF, and Modin
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
