{% set name = "narwhals" %}
{% set version = "1.31.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/narwhals-{{ version }}.tar.gz
  sha256: 333472e2562343dfdd27407ec9b5114a07c81d0416794e4ac6b703dd925c6a1a

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  skip: True  #[py<38]

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
  run_constrained:
    - pandas >=0.25.3
    - polars >=0.20.3
    - pyarrow >=11.0.0
    - pyspark >=3.5.0
    - dask >=2024.8

test:
  imports:
    - narwhals
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/narwhals-dev/narwhals
  dev_url: https://github.com/narwhals-dev/narwhals
  summary: Extremely lightweight compatibility layer between pandas, Polars, cuDF, and Modin
  license: MIT
  license_file: LICENSE.md
  license_family: MIT
  description: |
    Narwhals is an extremely lightweight compatibility layer between pandas, Polars, cuDF, and Modin.
    It allows you to write code that works with all of these libraries without having to worry about
    the differences between them.
  doc_url: https://narwhals-dev.github.io/narwhals/


extra:
  recipe-maintainers:
    - MarcoGorelli
    - thewchan
