{% set name = "narwhals" %}
{% set version = "1.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/narwhals-{{ version }}.tar.gz
  sha256: 8262d77afec11960852e3f24d250e882575d9115ce7076df20b7c3bdce1281eb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - narwhals
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://marcogorelli.github.io/narwhals/
  dev_url: https://github.com/MarcoGorelli/narwhals
  summary: Extremely lightweight compatibility layer between pandas, Polars, cuDF, and Modin
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - MarcoGorelli
    - thewchan
